services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    # image: nginx:alpine3.22
    env_file: .env
    ports:
      - "8080:80"
    restart: always
    secrets:
      - db_password
    networks:
      - inception
    # volumes:
      # - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./requirements/nginx/html/index.html:/var/www/html/index.html
      # - wordpress:/var/www/html
      
networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt

# volumes:
#   wordpress:
    # driver : local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/wordpress
    #   o: bind